Fix atmosphere embedded example
[TODO] generated start script causes following exception:
org.fusesource.scalate.TemplateException: Template file extension missing. Cannot determine which template processor to use.